#define COMPANY_NAME  "snctln"
#define COPYRIGHT_BLURB  "Copyright (c) 2008"

#define PRODUCT_NAME  "Manilla 2D Customizer"

#define PRODUCT_VERSION_MAJOR   0
#define PRODUCT_VERSION_MINOR   5
#define PRODUCT_VERSION_BUILD   0
#define PRODUCT_VERSION_QFE     43

#define FILE_VERSION_MAJOR   PRODUCT_VERSION_MAJOR
#define FILE_VERSION_MINOR   PRODUCT_VERSION_MINOR
#define FILE_VERSION_BUILD   PRODUCT_VERSION_BUILD
#define FILE_VERSION_QFE     PRODUCT_VERSION_QFE

